name: Consume Helm Chart

on:
  workflow_dispatch:
    inputs:
      chart:
        type: string
        required: true
      version:
        type: string
        required: true

jobs:
  consume:
    name: Consume
    runs-on:
      - ubuntu-latest
    env:
      REGISTRY: ghcr.io
    steps:
      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Login to Container Registry
        env:
          GITHUB_RUNNER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo ${GITHUB_RUNNER_TOKEN} | helm registry login ${REGISTRY}/${{ github.repository_owner }} --username "github-actions" --password-stdin

      - name: Test Chart
        run: helm template test-release oci://${{ github.repository }}/${{ inputs.chart }} --version ${{ inputs.version }}